# スタック
# テンプレートによって管理(作成、削除、更新)されるAWSリソースのこと
# テンプレート
# スタックの設計図にあたり、どのAWSリソースをどう起動するのかを記述したファイル
# リソースの依存関係はCloudFormationが自動判別する
AWSTemplateFormatVersion: 2010-09-09
Description: Wordpress template for VPC

# スタックを構成するAWSリソースを定義する
Resources:
  # 論理IDテンプレート内で一意である必要がある
  WordPressVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      InstanceTenancy: default
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: "Name"
          Value: "wordpress-vpc"

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.0.0/24
      VpcId: !Ref WordPressVPC
      AvailabilityZone: "ap-northeast-1"
      # AvailabilityZone: !Select [ 0, !GetAZs ]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: "Name"
          Value: "PublicSubnet1"

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.1.0/24
      VpcId: !Ref WordPressVPC
      AvailabilityZone: "ap-northeast-1"
      # AvailabilityZone: !Select [ 0, !GetAZs ]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: "Name"
          Value: "PublicSubnet2"

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.2.0/24
      VpcId: !Ref WordPressVPC
      AvailabilityZone: "ap-northeast-1"
      # AvailabilityZone: !Select [ 0, !GetAZs ]
      Tags:
        - Key: "Name"
          Value: "PrivateSubnet1"

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.3.0/24
      VpcId: !Ref WordPressVPC
      AvailabilityZone: "ap-northeast-1"
      # AvailabilityZone: !Select [ 0, !GetAZs ]
      Tags:
        - Key: "Name"
          Value: "PrivateSubnet2"

  WordPressVPCIGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: wp-cfn

  WordPressVPCIGWAttach:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref WordPressVPCIGW
      VpcId: !Ref WordPressVPC

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref WordPressVPC
      Tags:
        - Key: Name
          Value: Public Route

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: WordPressVPCIGW
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref WordPressVPCIGW

  PublicSubnet1Association:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1
      RouteTableId: !Ref PublicRouteTable

  PublicSubnet2Association:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet2
      RouteTableId: !Ref PublicRouteTable

  Outputs:
    VPCID:
      Description: VPC ID
      Value: !Ref WordPressVPC
      Export:
        Name: !Sub ${AWS::StackName}-VPCID

    PublicSubnet1:
      Description: PublicSubnet1
      Value: !Ref PublicSubnet1
      Export:
        Name: !Sub ${AWS::StackName}-PublicSubnet1

    PublicSubnet2:
      Description: PublicSubnet2
      Value: !Ref PublicSubnet2
      Export:
        Name: !Sub ${AWS::StackName}-PublicSubnet2

    PrivateSubnet1:
      Description: PrivateSubnet1
      Value: !Ref PrivateSubnet1
      Export:
        Name: !Sub ${AWS::StackName}-PrivateSubnet1

    PrivateSubnet2:
      Description: PrivateSubnet2
      Value: !Ref PrivateSubnet2
      Export:
        Name: !Sub ${AWS::StackName}-PrivateSubnet2
