# スタック
# テンプレートによって管理(作成、削除、更新)されるAWSリソースのこと
# テンプレート
# スタックの設計図にあたり、どのAWSリソースをどう起動するのかを記述したファイル
# リソースの依存関係はCloudFormationが自動判別する
AWSTemplateFormatVersion: 2010-09-09
Description: Wordpress template for VPC

# スタックを構成するAWSリソースを定義する
Resources:
  # 論理IDテンプレート内で一意である必要がある
  WordPressVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      InstanceTenancy: default
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: wordpress-vpc

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.0.0/24
      # !Ref: Parametersセクションで指定したパラメータの参照、Resourcesセクションで指定したリソースの参照で使用する
      #       同じスタックのリソース、もしくはパラメータを参照したい場合に使用する
      # WordPressVPCリソースを参照
      VpcId: !Ref WordPressVPC
      AvailabilityZone: !Select [ 0, !GetAZs ]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: PublicSubnet1

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.2.0/24
      VpcId: !Ref WordPressVPC
      AvailabilityZone: !Select [ 1, !GetAZs ]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: PublicSubnet2

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.4.0/24
      VpcId: !Ref WordPressVPC
      AvailabilityZone: !Select [ 0, !GetAZs ]
      Tags:
        - Key: Name
          Value: PrivateSubnet1

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.5.0/24
      VpcId: !Ref WordPressVPC
      AvailabilityZone: !Select [ 1, !GetAZs ]
      Tags:
        - Key: Name
          Value: PrivateSubnet2

  WordPressVPCIGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: wp-cfn

  WordPressVPCIGWAttach:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      # WordPressVPCIGWリソースを参照
      InternetGatewayId: !Ref WordPressVPCIGW
      VpcId: !Ref WordPressVPC

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref WordPressVPC
      Tags:
        - Key: Name
          Value: Public Route

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: WordPressVPCIGW
    Properties:
      # PublicRouteTableリソースを参照
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref WordPressVPCIGW

  PublicSubnet1Association:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1
      RouteTableId: !Ref PublicRouteTable

  PublicSubnet2Association:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet2
      RouteTableId: !Ref PublicRouteTable

# 別のスタックで値を参照(ImportValue)する、CloudFormationコンソールに値を出力するのに使用
Outputs:
  VPCID:
    Description: VPC ID
    Value: !Ref WordPressVPC
    Export:
      Name: !Sub ${AWS::StackName}-VPCID

  PublicSubnet1:
    Description: PublicSubnet1
    # PublicSubnet1リソースを参照
    Value: !Ref PublicSubnet1
    Export:
      Name: !Sub ${AWS::StackName}-PublicSubnet1

  PublicSubnet2:
    Description: PublicSubnet2
    # PublicSubnet2リソースを参照
    Value: !Ref PublicSubnet2
    Export:
      Name: !Sub ${AWS::StackName}-PublicSubnet2

  PrivateSubnet1:
    Description: PrivateSubnet1
    # PrivateSubnet1リソースを参照
    Value: !Ref PrivateSubnet1
    Export:
      Name: !Sub ${AWS::StackName}-PrivateSubnet1

  PrivateSubnet2:
    Description: PrivateSubnet2
    # PrivateSubnet2リソースを参照
    Value: !Ref PrivateSubnet2
    Export:
      Name: !Sub ${AWS::StackName}-PrivateSubnet2
